# **Section 1 - Dataset Overview**

In [1]:
import pandas as pd
import numpy as np

# Load dataset
df = pd.read_csv("cs-training.csv")

df.head()

,Unnamed: 0,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
0,1,1,0.766127,45,2,0.802982,9120.0,13,0,6,0,2.0
1,2,0,0.957151,40,0,0.121876,2600.0,4,0,0,0,1.0
2,3,0,0.658180,38,1,0.085113,3042.0,2,1,0,0,0.0
3,4,0,0.233810,30,0,0.036050,3300.0,5,0,0,0,0.0
4,5,0,0.907239,49,1,0.024926,63588.0,7,0,1,0,0.0

In [2]:
df.shape

(150000, 12)

In [3]:
df.columns

Index(['Unnamed: 0', 'SeriousDlqin2yrs',
       'RevolvingUtilizationOfUnsecuredLines', 'age',
       'NumberOfTime30-59DaysPastDueNotWorse', 'DebtRatio', 'MonthlyIncome',
       'NumberOfOpenCreditLinesAndLoans', 'NumberOfTimes90DaysLate',
       'NumberRealEstateLoansOrLines', 'NumberOfTime60-89DaysPastDueNotWorse',
       'NumberOfDependents'],
      dtype='object')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 12 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   Unnamed: 0                            150000 non-null  int64
 1   SeriousDlqin2yrs                      150000 non-null  int64
 2   RevolvingUtilizationOfUnsecuredLines  150000 non-null  float64
 3   age                                   150000 non-null  int64
 4   NumberOfTime30-59DaysPastDueNotWorse  150000 non-null  int64
 5   DebtRatio                             150000 non-null  float64
 6   MonthlyIncome                         120269 non-null  float64
 7   NumberOfOpenCreditLinesAndLoans       150000 non-null  int64
 8   NumberOfTimes90DaysLate               150000 non-null  int64
 9   NumberRealEstateLoansOrLines          150000 non-null  int64
 10  NumberOfTime60-89DaysPastDueNotWorse  150000 non-null  int64
 11  NumberOfDependents                    146076 non-null  float64
dtypes: float64(4), int64(8)
memory usage: 13.7 MB

In [5]:
df.describe()

,Unnamed: 0,SeriousDlqin2yrs,RevolvingUtilizationOfUnsecuredLines,age,NumberOfTime30-59DaysPastDueNotWorse,DebtRatio,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberOfTimes90DaysLate,NumberRealEstateLoansOrLines,NumberOfTime60-89DaysPastDueNotWorse,NumberOfDependents
count,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,1.202690e+05,150000.000000,150000.000000,150000.000000,150000.000000,146076.000000
mean,75000.500000,0.066840,6.048438,52.295207,0.421033,353.005076,6.670221e+03,8.452760,0.265973,1.018240,0.240387,0.757222
std,43301.414527,0.249746,249.755371,14.771866,4.192781,2037.818523,1.438467e+04,5.145951,4.169304,1.129771,4.155179,1.115086
min,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000
25%,37500.750000,0.000000,0.029867,41.000000,0.000000,0.175074,3.400000e+03,5.000000,0.000000,0.000000,0.000000,0.000000
50%,75000.500000,0.000000,0.154181,52.000000,0.000000,0.366508,5.400000e+03,8.000000,0.000000,1.000000,0.000000,0.000000
75%,112500.250000,0.000000,0.559046,63.000000,0.000000,0.868254,8.249000e+03,11.000000,0.000000,2.000000,0.000000,1.000000
max,150000.000000,1.000000,50708.000000,109.000000,98.000000,329664.000000,3.008750e+06,58.000000,98.000000,54.000000,98.000000,20.000000

In [6]:
df["SeriousDlqin2yrs"].mean()

np.float64(0.06684)

# **SECTION 2 — Data Cleaning**

**Step 1 — Remove Unnecessary Column**

In [7]:
df.drop(columns=["Unnamed: 0"], inplace=True)

**Step 2 — Check Target Distribution Properly**

In [8]:
df["SeriousDlqin2yrs"].value_counts(normalize=True)

SeriousDlqin2yrs
0    0.93316
1    0.06684
Name: proportion, dtype: float64

**Step 3 — Check Extreme Values**

In [9]:
df[["RevolvingUtilizationOfUnsecuredLines", "DebtRatio"]].describe(percentiles=[0.95, 0.99])

       RevolvingUtilizationOfUnsecuredLines      DebtRatio
count                         150000.000000  150000.000000
mean                               6.048438     353.005076
std                              249.755371    2037.818523
min                                0.000000       0.000000
50%                                0.154181       0.366508
95%                                1.000000    2449.000000
99%                                1.092956    4979.040000
max                            50708.000000  329664.000000

**Step 4 — Check Income Distribution**

In [10]:
df["MonthlyIncome"].describe(percentiles=[0.95, 0.99])

count    1.202690e+05
mean     6.670221e+03
std      1.438467e+04
min      0.000000e+00
50%      5.400000e+03
95%      1.458760e+04
99%      2.500000e+04
max      3.008750e+06
Name: MonthlyIncome, dtype: float64

**Step 5 - Cap Revolving Utilization**

In [11]:
rev_cap = df["RevolvingUtilizationOfUnsecuredLines"].quantile(0.99)
df["RevolvingUtilizationOfUnsecuredLines"] = np.where(
    df["RevolvingUtilizationOfUnsecuredLines"] > rev_cap,
    rev_cap,
    df["RevolvingUtilizationOfUnsecuredLines"]
)

**Step 6 - Cap Debt Ratio**

In [12]:
debt_cap = df["DebtRatio"].quantile(0.99)
df["DebtRatio"] = np.where(
    df["DebtRatio"] > debt_cap,
    debt_cap,
    df["DebtRatio"]
)

**Step 7 - Cap Monthly Income (99th percentile)**

In [13]:
income_cap = df["MonthlyIncome"].quantile(0.99)
df["MonthlyIncome"] = np.where(
    df["MonthlyIncome"] > income_cap,
    income_cap,
    df["MonthlyIncome"]
)

**Step 8 - Fill Missing Monthly Income**

In [14]:
df["MonthlyIncome"].fillna(df["MonthlyIncome"].median(), inplace=True)

/tmp/ipykernel_319/4277719454.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["MonthlyIncome"].fillna(df["MonthlyIncome"].median(), inplace=True)

**Step 9 - Fill Missing Dependents**

In [15]:
df["NumberOfDependents"].fillna(df["NumberOfDependents"].median(), inplace=True)

/tmp/ipykernel_319/3939358075.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["NumberOfDependents"].fillna(df["NumberOfDependents"].median(), inplace=True)

In [16]:
df[["RevolvingUtilizationOfUnsecuredLines","DebtRatio","MonthlyIncome"]].describe(percentiles=[0.95,0.99])

       RevolvingUtilizationOfUnsecuredLines      DebtRatio  MonthlyIncome
count                         150000.000000  150000.000000  150000.000000
mean                               0.320496     316.548869    6160.991940
std                                0.352152     906.962222    3920.912328
min                                0.000000       0.000000       0.000000
50%                                0.154181       0.366508    5400.000000
95%                                1.000000    2449.000000   13500.000000
99%                                1.092954    4979.000400   23000.000000
max                                1.092956    4979.040000   25000.000000

In [17]:
df.isna().sum()

SeriousDlqin2yrs                        0
RevolvingUtilizationOfUnsecuredLines    0
age                                     0
NumberOfTime30-59DaysPastDueNotWorse    0
DebtRatio                               0
MonthlyIncome                           0
NumberOfOpenCreditLinesAndLoans         0
NumberOfTimes90DaysLate                 0
NumberRealEstateLoansOrLines            0
NumberOfTime60-89DaysPastDueNotWorse    0
NumberOfDependents                      0
dtype: int64

# **SECTION 3 — Risk Profiling**

**Step 1 — Confirm Portfolio Default Rate**

In [18]:
df["SeriousDlqin2yrs"].mean()

np.float64(0.06684)

**Step 2 — Create Age Groups**

In [19]:
df["age_group"] = pd.cut(
    df["age"],
    bins=[20,30,40,50,60,70,100],
    labels=["20-30","30-40","40-50","50-60","60-70","70+"]
)

In [20]:
age_risk = df.groupby("age_group")["SeriousDlqin2yrs"].mean()

age_risk

/tmp/ipykernel_319/1348789645.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  age_risk = df.groupby("age_group")["SeriousDlqin2yrs"].mean()

age_group
20-30    0.115646
30-40    0.098196
40-50    0.082570
50-60    0.061742
60-70    0.034714
70+      0.022527
Name: SeriousDlqin2yrs, dtype: float64

**Step 3 — Credit Utilization Risk**

In [21]:
df["utilization_band"] = pd.cut(
    df["RevolvingUtilizationOfUnsecuredLines"],
    bins=[0,0.3,0.6,0.9,2],
    labels=["Low","Medium","High","Very High"]
)

In [22]:
util_risk = df.groupby("utilization_band")["SeriousDlqin2yrs"].mean()

util_risk

/tmp/ipykernel_319/2427305882.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  util_risk = df.groupby("utilization_band")["SeriousDlqin2yrs"].mean()

utilization_band
Low          0.021231
Medium       0.066798
High         0.133030
Very High    0.223529
Name: SeriousDlqin2yrs, dtype: float64

**Step 4 — Delinquency History Risk**

In [23]:
delinq_risk = df.groupby("NumberOfTimes90DaysLate")["SeriousDlqin2yrs"].mean()

delinq_risk.head(10)

NumberOfTimes90DaysLate
0    0.046265
1    0.336639
2    0.499035
3    0.577211
4    0.670103
5    0.633588
6    0.600000
7    0.815789
8    0.714286
9    0.736842
Name: SeriousDlqin2yrs, dtype: float64

# **SECTION 4 — Portfolio Risk Segmentation**

**Step 1 — Create Delinquency Indicator**

In [24]:
df["has_delinquency"] = np.where(
    df["NumberOfTimes90DaysLate"] > 0,
    1,
    0
)

**Step 2 — Create Risk Score**

In [25]:
df["risk_score"] = (
    df["RevolvingUtilizationOfUnsecuredLines"]*0.4 +
    df["DebtRatio"]*0.2 +
    df["has_delinquency"]*0.4
)

**Step 3 — Segment Borrowers**

In [26]:
df["risk_segment"] = pd.qcut(
    df["risk_score"],
    q=3,
    labels=["Low Risk","Medium Risk","High Risk"]
)

**Step 4 — Evaluate Segments**

In [27]:
risk_summary = df.groupby("risk_segment")["SeriousDlqin2yrs"].agg(
    ["count","mean"]
)

risk_summary["default_rate_pct"] = risk_summary["mean"]*100

risk_summary

/tmp/ipykernel_319/1885477110.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  risk_summary = df.groupby("risk_segment")["SeriousDlqin2yrs"].agg(

              count     mean  default_rate_pct
risk_segment
Low Risk      50000  0.01478             1.478
Medium Risk   50000  0.05720             5.720
High Risk     50000  0.12854            12.854

# **SECTION 5 — Credit Approval Strategy Simulation**

**Step 1 — Baseline Portfolio Risk**

In [28]:
baseline_default = df["SeriousDlqin2yrs"].mean()

baseline_default

np.float64(0.06684)

**Step 2 — Scenario: Reject High-Risk Borrowers**

In [29]:
scenario_1 = df[df["risk_segment"] != "High Risk"]

scenario_1["SeriousDlqin2yrs"].mean()

np.float64(0.03599)

In [30]:
#Approval Share

len(scenario_1) / len(df)

0.6666666666666666

**Step 3 — Scenario: Approve Only Low-Risk Borrowers**

In [31]:
scenario_2 = df[df["risk_segment"] == "Low Risk"]

scenario_2["SeriousDlqin2yrs"].mean()

np.float64(0.01478)

In [32]:
#Approval Share

len(scenario_2) / len(df)

0.3333333333333333

# **SECTION 6 — Business Insights**

**1. Borrower risk is highly concentrated**

Portfolio analysis revealed significant differences in borrower risk across segments. High-risk borrowers exhibit a 12.85% default rate, compared to 1.48% for low-risk borrowers, indicating that risk is concentrated in specific borrower groups rather than evenly distributed across the portfolio.


**2. Credit utilisation is a strong early warning signal**

Borrowers with very high credit utilisation (>90%) default at 22.35%, nearly 10 times higher than low-utilisation borrowers. This suggests that credit utilisation is one of the most powerful behavioural indicators of financial distress.


**3. Prior delinquency history dramatically increases default probability**

Borrowers with even one prior 90-day delinquency exhibit a 33.6% default probability, compared to 4.6% for borrowers with no delinquency history. Delinquency history therefore represents the strongest predictor of future default.

**4. Younger borrowers show higher credit risk**

Borrowers aged 20–30 default at 11.5%, nearly five times higher than borrowers above age 70. This reflects typical credit lifecycle behaviour where younger borrowers have shorter credit histories and less stable income profiles.

**5. Risk-based approval policies can significantly reduce portfolio losses**

Simulating approval policies showed that excluding high-risk borrowers could reduce overall portfolio default rates from 6.68% to 3.60%, representing a 46% reduction in defaults while still approving two-thirds of applicants.

# **SECTION 7 — Business Recommendations**

**1. Implement risk-segmented approval thresholds**

Financial institutions should incorporate risk segmentation into credit approval workflows. Rejecting high-risk borrowers identified through utilisation, delinquency history, and debt ratio indicators could significantly reduce portfolio default rates.

**2. Monitor credit utilisation as a leading risk indicator**

Credit utilisation should be closely monitored as an early warning signal for financial distress. Borrowers with utilisation above 90% should trigger risk monitoring or credit limit controls.

**3. Apply stricter policies for borrowers with prior delinquencies**

Given the sharp increase in default probability for borrowers with past delinquencies, stricter underwriting thresholds or additional verification should be applied for these applicants.

**4. Adopt balanced credit strategies instead of extreme rejection policies**

While approving only low-risk borrowers reduces defaults to 1.48%, it also dramatically reduces lending volume. A balanced policy that excludes high-risk borrowers provides the best trade-off between risk control and business growth.

**5. Use data-driven credit decision frameworks**

The analysis demonstrates that simple risk indicators can meaningfully improve lending outcomes. Integrating data-driven segmentation into credit decision systems can improve both risk management and portfolio profitability.